# Generated by Django 5.1.2 on 2024-10-13 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
