# Generated by Django 5.1.2 on 2024-10-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_usuario_edad_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
