# Generated by Django 5.1.2 on 2024-10-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_usuario_atendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=11)),
                ('edad', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
            ],
        ),
    ]
