# Generated by Django 5.1.2 on 2024-10-15 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_usuarioatendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioatendido',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
