# Generated by Django 5.1.2 on 2024-10-16 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_alter_usuarioatendido_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('usuarios', models.ManyToManyField(related_name='registro_diario', to='Index.usuario')),
            ],
        ),
    ]
