# Generated by Django 5.1.2 on 2024-10-18 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0006_registrohoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='usuarioatendido',
            name='cedula',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
