# Generated by Django 5.1.2 on 2024-11-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0008_alter_registrohoy_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioatendido',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
